name: FireSystemPlugin
main: ru.hse.edu.stalivanov.fireplugin.PluginMain
version: 0.0.1
api-version: 1.20
author: tokel-tokel
commands:
  alarm:
    usage: /alarm
  stickypiston:
    usage: /stickypiston
  smokedetector:
    usage: /smokedetector
  firesystem:
    usage: /firesystem
  givetool:
    usage: /givetool
